name: Setup Hayagriva
description: 🏷️ Installs the Hayagriva CLI for GitHub Actions

branding:
  icon: play
  color: blue

inputs:
  hayagriva-version:
    description: Which version of Hayagriva to install. This can be an exact version specifier such as '1.5.1' or a semver range like '~0.5.0' or '0.x'. Use 'latest' to always install the latest release. Defaults to 'latest'.
    default: latest
  hayagriva-token:
    description: The GitHub token to use when fetching the version list from bytecodealliance/hayagriva. You shouldn't have to touch this. The default is the 'github.token' if you're on github.com or unauthenticated (rate limited) if you're not on github.com.
    default: ${{ github.server_url == 'https://github.com' && github.token || '' }}
  cache:
    description: Whether or not to use the workflow cache to cache the compiled 'hayagriva' binary for future runs.
    default: true

outputs:
  hayagriva-version:
    description: The version of Hayagriva that was installed. This will be something like '1.5.1' or similar.
    value: ${{ steps.setup-hayagriva.outputs.hayagriva-version }}
  cache-hit:
    description: Whether or not Hayagriva was restored from the runner's cache or download anew.
    value: ${{ steps.setup-hayagriva.outputs.cache-hit }}

runs:
  using: composite
  steps:
    - uses: cargo-bins/cargo-binstall@main
    - id: setup-hayagriva
      run: node "$GITHUB_ACTION_PATH/dist/main.js"
      env:
        INPUT_HAYAGRIVA-VERSION: ${{ inputs.hayagriva-version }}
        INPUT_HAYAGRIVA-TOKEN: ${{ inputs.hayagriva-token }}
        INPUT_CACHE-HIT: ${{ inputs.cache-hit }}
